name = "cloudflare-d1-template"
main = "src/index.js"
compatibility_date = "2024-06-10"

[[routes]]
pattern = "d1-template.aivillage.dev"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "d1-template-db"
database_id = "YOUR-DATABASE-ID-HERE"
